/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as YourCartImport } from './routes/yourCart'
import { Route as LoginImport } from './routes/login'
import { Route as IndexImport } from './routes/index'
import { Route as ProductsIndexImport } from './routes/products/index'
import { Route as AdminIndexImport } from './routes/admin/index'
import { Route as ProductsIdIndexImport } from './routes/products/$id/index'
import { Route as AdminUsersIndexImport } from './routes/admin/users/index'
import { Route as AdminSpecsIndexImport } from './routes/admin/specs/index'
import { Route as AdminItemsIndexImport } from './routes/admin/items/index'
import { Route as AdminCategoriesIndexImport } from './routes/admin/categories/index'
import { Route as AdminBrandsIndexImport } from './routes/admin/brands/index'
import { Route as AdminSpecsEditSpecsImport } from './routes/admin/specs/editSpecs'
import { Route as AdminSpecsAddSpecsImport } from './routes/admin/specs/addSpecs'
import { Route as AdminItemsSearchItemImport } from './routes/admin/items/searchItem'
import { Route as AdminItemsAddItemImport } from './routes/admin/items/addItem'
import { Route as AdminCategoriesAddCategoriesImport } from './routes/admin/categories/addCategories'
import { Route as AdminCategoriesSearchCategoryImport } from './routes/admin/categories/SearchCategory'
import { Route as AdminBrandsEditBrandsImport } from './routes/admin/brands/editBrands'
import { Route as AdminBrandsAddBrandsImport } from './routes/admin/brands/addBrands'
import { Route as ProductsCategoriesIdIndexImport } from './routes/products/categories/$id/index'
import { Route as ProductsBrandsIdIndexImport } from './routes/products/brands/$id/index'
import { Route as ProductsIdReviewsIndexImport } from './routes/products/$id/reviews/index'
import { Route as ProductsIdReviewsReviewIdIndexImport } from './routes/products/$id/reviews/$reviewId/index'
import { Route as AdminItemsEditItemIdIndexImport } from './routes/admin/items/editItem/$id/index'
import { Route as AdminCategoriesEditCategoryIdIndexImport } from './routes/admin/categories/editCategory/$id/index'

// Create/Update Routes

const YourCartRoute = YourCartImport.update({
  path: '/yourCart',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ProductsIndexRoute = ProductsIndexImport.update({
  path: '/products/',
  getParentRoute: () => rootRoute,
} as any)

const AdminIndexRoute = AdminIndexImport.update({
  path: '/admin/',
  getParentRoute: () => rootRoute,
} as any)

const ProductsIdIndexRoute = ProductsIdIndexImport.update({
  path: '/products/$id/',
  getParentRoute: () => rootRoute,
} as any)

const AdminUsersIndexRoute = AdminUsersIndexImport.update({
  path: '/admin/users/',
  getParentRoute: () => rootRoute,
} as any)

const AdminSpecsIndexRoute = AdminSpecsIndexImport.update({
  path: '/admin/specs/',
  getParentRoute: () => rootRoute,
} as any)

const AdminItemsIndexRoute = AdminItemsIndexImport.update({
  path: '/admin/items/',
  getParentRoute: () => rootRoute,
} as any)

const AdminCategoriesIndexRoute = AdminCategoriesIndexImport.update({
  path: '/admin/categories/',
  getParentRoute: () => rootRoute,
} as any)

const AdminBrandsIndexRoute = AdminBrandsIndexImport.update({
  path: '/admin/brands/',
  getParentRoute: () => rootRoute,
} as any)

const AdminSpecsEditSpecsRoute = AdminSpecsEditSpecsImport.update({
  path: '/admin/specs/editSpecs',
  getParentRoute: () => rootRoute,
} as any)

const AdminSpecsAddSpecsRoute = AdminSpecsAddSpecsImport.update({
  path: '/admin/specs/addSpecs',
  getParentRoute: () => rootRoute,
} as any)

const AdminItemsSearchItemRoute = AdminItemsSearchItemImport.update({
  path: '/admin/items/searchItem',
  getParentRoute: () => rootRoute,
} as any)

const AdminItemsAddItemRoute = AdminItemsAddItemImport.update({
  path: '/admin/items/addItem',
  getParentRoute: () => rootRoute,
} as any)

const AdminCategoriesAddCategoriesRoute =
  AdminCategoriesAddCategoriesImport.update({
    path: '/admin/categories/addCategories',
    getParentRoute: () => rootRoute,
  } as any)

const AdminCategoriesSearchCategoryRoute =
  AdminCategoriesSearchCategoryImport.update({
    path: '/admin/categories/SearchCategory',
    getParentRoute: () => rootRoute,
  } as any)

const AdminBrandsEditBrandsRoute = AdminBrandsEditBrandsImport.update({
  path: '/admin/brands/editBrands',
  getParentRoute: () => rootRoute,
} as any)

const AdminBrandsAddBrandsRoute = AdminBrandsAddBrandsImport.update({
  path: '/admin/brands/addBrands',
  getParentRoute: () => rootRoute,
} as any)

const ProductsCategoriesIdIndexRoute = ProductsCategoriesIdIndexImport.update({
  path: '/products/categories/$id/',
  getParentRoute: () => rootRoute,
} as any)

const ProductsBrandsIdIndexRoute = ProductsBrandsIdIndexImport.update({
  path: '/products/brands/$id/',
  getParentRoute: () => rootRoute,
} as any)

const ProductsIdReviewsIndexRoute = ProductsIdReviewsIndexImport.update({
  path: '/products/$id/reviews/',
  getParentRoute: () => rootRoute,
} as any)

const ProductsIdReviewsReviewIdIndexRoute =
  ProductsIdReviewsReviewIdIndexImport.update({
    path: '/products/$id/reviews/$reviewId/',
    getParentRoute: () => rootRoute,
  } as any)

const AdminItemsEditItemIdIndexRoute = AdminItemsEditItemIdIndexImport.update({
  path: '/admin/items/editItem/$id/',
  getParentRoute: () => rootRoute,
} as any)

const AdminCategoriesEditCategoryIdIndexRoute =
  AdminCategoriesEditCategoryIdIndexImport.update({
    path: '/admin/categories/editCategory/$id/',
    getParentRoute: () => rootRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/yourCart': {
      id: '/yourCart'
      path: '/yourCart'
      fullPath: '/yourCart'
      preLoaderRoute: typeof YourCartImport
      parentRoute: typeof rootRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminIndexImport
      parentRoute: typeof rootRoute
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsIndexImport
      parentRoute: typeof rootRoute
    }
    '/admin/brands/addBrands': {
      id: '/admin/brands/addBrands'
      path: '/admin/brands/addBrands'
      fullPath: '/admin/brands/addBrands'
      preLoaderRoute: typeof AdminBrandsAddBrandsImport
      parentRoute: typeof rootRoute
    }
    '/admin/brands/editBrands': {
      id: '/admin/brands/editBrands'
      path: '/admin/brands/editBrands'
      fullPath: '/admin/brands/editBrands'
      preLoaderRoute: typeof AdminBrandsEditBrandsImport
      parentRoute: typeof rootRoute
    }
    '/admin/categories/SearchCategory': {
      id: '/admin/categories/SearchCategory'
      path: '/admin/categories/SearchCategory'
      fullPath: '/admin/categories/SearchCategory'
      preLoaderRoute: typeof AdminCategoriesSearchCategoryImport
      parentRoute: typeof rootRoute
    }
    '/admin/categories/addCategories': {
      id: '/admin/categories/addCategories'
      path: '/admin/categories/addCategories'
      fullPath: '/admin/categories/addCategories'
      preLoaderRoute: typeof AdminCategoriesAddCategoriesImport
      parentRoute: typeof rootRoute
    }
    '/admin/items/addItem': {
      id: '/admin/items/addItem'
      path: '/admin/items/addItem'
      fullPath: '/admin/items/addItem'
      preLoaderRoute: typeof AdminItemsAddItemImport
      parentRoute: typeof rootRoute
    }
    '/admin/items/searchItem': {
      id: '/admin/items/searchItem'
      path: '/admin/items/searchItem'
      fullPath: '/admin/items/searchItem'
      preLoaderRoute: typeof AdminItemsSearchItemImport
      parentRoute: typeof rootRoute
    }
    '/admin/specs/addSpecs': {
      id: '/admin/specs/addSpecs'
      path: '/admin/specs/addSpecs'
      fullPath: '/admin/specs/addSpecs'
      preLoaderRoute: typeof AdminSpecsAddSpecsImport
      parentRoute: typeof rootRoute
    }
    '/admin/specs/editSpecs': {
      id: '/admin/specs/editSpecs'
      path: '/admin/specs/editSpecs'
      fullPath: '/admin/specs/editSpecs'
      preLoaderRoute: typeof AdminSpecsEditSpecsImport
      parentRoute: typeof rootRoute
    }
    '/admin/brands/': {
      id: '/admin/brands/'
      path: '/admin/brands'
      fullPath: '/admin/brands'
      preLoaderRoute: typeof AdminBrandsIndexImport
      parentRoute: typeof rootRoute
    }
    '/admin/categories/': {
      id: '/admin/categories/'
      path: '/admin/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesIndexImport
      parentRoute: typeof rootRoute
    }
    '/admin/items/': {
      id: '/admin/items/'
      path: '/admin/items'
      fullPath: '/admin/items'
      preLoaderRoute: typeof AdminItemsIndexImport
      parentRoute: typeof rootRoute
    }
    '/admin/specs/': {
      id: '/admin/specs/'
      path: '/admin/specs'
      fullPath: '/admin/specs'
      preLoaderRoute: typeof AdminSpecsIndexImport
      parentRoute: typeof rootRoute
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersIndexImport
      parentRoute: typeof rootRoute
    }
    '/products/$id/': {
      id: '/products/$id/'
      path: '/products/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof ProductsIdIndexImport
      parentRoute: typeof rootRoute
    }
    '/products/$id/reviews/': {
      id: '/products/$id/reviews/'
      path: '/products/$id/reviews'
      fullPath: '/products/$id/reviews'
      preLoaderRoute: typeof ProductsIdReviewsIndexImport
      parentRoute: typeof rootRoute
    }
    '/products/brands/$id/': {
      id: '/products/brands/$id/'
      path: '/products/brands/$id'
      fullPath: '/products/brands/$id'
      preLoaderRoute: typeof ProductsBrandsIdIndexImport
      parentRoute: typeof rootRoute
    }
    '/products/categories/$id/': {
      id: '/products/categories/$id/'
      path: '/products/categories/$id'
      fullPath: '/products/categories/$id'
      preLoaderRoute: typeof ProductsCategoriesIdIndexImport
      parentRoute: typeof rootRoute
    }
    '/admin/categories/editCategory/$id/': {
      id: '/admin/categories/editCategory/$id/'
      path: '/admin/categories/editCategory/$id'
      fullPath: '/admin/categories/editCategory/$id'
      preLoaderRoute: typeof AdminCategoriesEditCategoryIdIndexImport
      parentRoute: typeof rootRoute
    }
    '/admin/items/editItem/$id/': {
      id: '/admin/items/editItem/$id/'
      path: '/admin/items/editItem/$id'
      fullPath: '/admin/items/editItem/$id'
      preLoaderRoute: typeof AdminItemsEditItemIdIndexImport
      parentRoute: typeof rootRoute
    }
    '/products/$id/reviews/$reviewId/': {
      id: '/products/$id/reviews/$reviewId/'
      path: '/products/$id/reviews/$reviewId'
      fullPath: '/products/$id/reviews/$reviewId'
      preLoaderRoute: typeof ProductsIdReviewsReviewIdIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  LoginRoute,
  YourCartRoute,
  AdminIndexRoute,
  ProductsIndexRoute,
  AdminBrandsAddBrandsRoute,
  AdminBrandsEditBrandsRoute,
  AdminCategoriesSearchCategoryRoute,
  AdminCategoriesAddCategoriesRoute,
  AdminItemsAddItemRoute,
  AdminItemsSearchItemRoute,
  AdminSpecsAddSpecsRoute,
  AdminSpecsEditSpecsRoute,
  AdminBrandsIndexRoute,
  AdminCategoriesIndexRoute,
  AdminItemsIndexRoute,
  AdminSpecsIndexRoute,
  AdminUsersIndexRoute,
  ProductsIdIndexRoute,
  ProductsIdReviewsIndexRoute,
  ProductsBrandsIdIndexRoute,
  ProductsCategoriesIdIndexRoute,
  AdminCategoriesEditCategoryIdIndexRoute,
  AdminItemsEditItemIdIndexRoute,
  ProductsIdReviewsReviewIdIndexRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/login",
        "/yourCart",
        "/admin/",
        "/products/",
        "/admin/brands/addBrands",
        "/admin/brands/editBrands",
        "/admin/categories/SearchCategory",
        "/admin/categories/addCategories",
        "/admin/items/addItem",
        "/admin/items/searchItem",
        "/admin/specs/addSpecs",
        "/admin/specs/editSpecs",
        "/admin/brands/",
        "/admin/categories/",
        "/admin/items/",
        "/admin/specs/",
        "/admin/users/",
        "/products/$id/",
        "/products/$id/reviews/",
        "/products/brands/$id/",
        "/products/categories/$id/",
        "/admin/categories/editCategory/$id/",
        "/admin/items/editItem/$id/",
        "/products/$id/reviews/$reviewId/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/yourCart": {
      "filePath": "yourCart.tsx"
    },
    "/admin/": {
      "filePath": "admin/index.tsx"
    },
    "/products/": {
      "filePath": "products/index.tsx"
    },
    "/admin/brands/addBrands": {
      "filePath": "admin/brands/addBrands.tsx"
    },
    "/admin/brands/editBrands": {
      "filePath": "admin/brands/editBrands.tsx"
    },
    "/admin/categories/SearchCategory": {
      "filePath": "admin/categories/SearchCategory.tsx"
    },
    "/admin/categories/addCategories": {
      "filePath": "admin/categories/addCategories.tsx"
    },
    "/admin/items/addItem": {
      "filePath": "admin/items/addItem.tsx"
    },
    "/admin/items/searchItem": {
      "filePath": "admin/items/searchItem.tsx"
    },
    "/admin/specs/addSpecs": {
      "filePath": "admin/specs/addSpecs.tsx"
    },
    "/admin/specs/editSpecs": {
      "filePath": "admin/specs/editSpecs.tsx"
    },
    "/admin/brands/": {
      "filePath": "admin/brands/index.tsx"
    },
    "/admin/categories/": {
      "filePath": "admin/categories/index.tsx"
    },
    "/admin/items/": {
      "filePath": "admin/items/index.tsx"
    },
    "/admin/specs/": {
      "filePath": "admin/specs/index.tsx"
    },
    "/admin/users/": {
      "filePath": "admin/users/index.tsx"
    },
    "/products/$id/": {
      "filePath": "products/$id/index.tsx"
    },
    "/products/$id/reviews/": {
      "filePath": "products/$id/reviews/index.tsx"
    },
    "/products/brands/$id/": {
      "filePath": "products/brands/$id/index.tsx"
    },
    "/products/categories/$id/": {
      "filePath": "products/categories/$id/index.tsx"
    },
    "/admin/categories/editCategory/$id/": {
      "filePath": "admin/categories/editCategory/$id/index.tsx"
    },
    "/admin/items/editItem/$id/": {
      "filePath": "admin/items/editItem/$id/index.tsx"
    },
    "/products/$id/reviews/$reviewId/": {
      "filePath": "products/$id/reviews/$reviewId/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
